title: Reynell Bobihis Portfolio Website
author:
  name: Reynell Bobihis
metadata:
    description: 'Curiculum Vitae made with Grav.'

# Header customization
header:
  title: I'm Reynell Bobihis.
  description: I'm a Manila based <span>web developer</span> and <span>graphic designer</span> creating awesome and effective visual identities for companies of all sizes. Let's <a class="smoothscroll" href="#about">start scrolling</a> and learn more <a class="smoothscroll" href="#about">about me</a>.
copyright:
    - line: &copy; Copyright 2014 HireReynell
    - line: Design by <a title="Styleshout" href="http://www.styleshout.com/">Styleshout</a>
social:
- url: "https://facebook.com/reynellbobihis"
  icon: facebook
- url: "https://twitter.com/reynellbobihis"
  icon: twitter
- url: "https://www.linkedin.com/in/reynellbobihis/"
  icon: linkedin
- url: "http://last.fm/user/reynellbobihis"
  icon: lastfm
- url: "https://open.spotify.com/user/reynellbobihis"
  icon: spotify


# HOW TO CREATE A VALID ID TO USE:
# Go to www.twitter.com and sign in as normal, go to your settings page.
# Go to "Widgets" on the left hand side.
# Create a new widget for what you need eg "user time line" or "search" etc.
# Feel free to check "exclude replies" if you don't want replies in results.
# Now go back to settings page, and then go back to widgets page and
# you should see the widget you just created. Click edit.
# Look at the URL in your web browser, you will see a long number like this:
# 657554810648948736
# Use this as your ID below instead!

twitter:
  id: '657554810648948736' # Your widget ID
  domId: 'tw-widget1' # HTML ID used in code
  maxTweets: 3 # How many tweets to display
  enableLinks: 'true' # Enable links
  showInteraction: 'false' # Show interaction
  showImages: 'false'  # Show images
  showUser: 'false' # Show user name
