title: Grav
author:
  name: Joe Bloggs
  email: 'joe@test.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
    
# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Links to include in navigation
# For external links add external: true
links:
  - title: About
    url: '#about'
  - title: Download
    url: '#download'
  - title: Contact
    url: '#contact'
